language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-27
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

jobs:
  include:
    # Build and test in one script for faster builds
    - stage: Build And Test
      language: android
      before_script: set -o pipefail
      script: ./gradlew assemble testDebugUnitTest 2>&1 | tee travisOutput.txt

    #=============================================

    # Build of app without any other task
    - stage: Build
      language: android
      script: ./gradlew assemble